### PR TITLE
letloop.xyz feed is buggy.

### PR DESCRIPTION
**Pull request by amirouche**

### CODE REVIEW

**Comment by amirouche** [comment]
@lassik @arthurgleckler the feed of my blog is buggy it repost old post everytime I do a new post or something along that line. I will try to fix the blog engine. In the meantime can you remove it from the feed.

I hope it does not upset everybody already.

**Comment by amirouche** [comment]
By the way, how can I run the planet on in local?

**Comment by amirouche** [comment]
FWIW, I pushed a fix on letloop.xyz. I reversed the order of the items in the feed to make the last item appear first. See https://letloop.xyz/feed.xml

**Comment by amirouche** [comment]
Let's wait, maybe it will planet scheme.

**Comment by amirouche** [comment]
https://planet.scheme.org/ is still borked.

**Comment by lassik** [comment]
(This PR continues from #2 and #3)

> the feed of my blog is buggy it repost old post everytime I do a new post or something along that line. I will try to fix the blog engine. In the meantime can you remove it from the feed.

Sure, merged.

> I hope it does not upset everybody already.

No-one has complained. Our Planet has many other problems, anyway.

> By the way, how can I run the planet in local?

We're using Planet Venus, an old, unmaintained planet engine written in Python:

* https://intertwingly.net/code/venus/docs/
* https://intertwingly.net/code/venus/
* https://packages.debian.org/buster/planet-venus

Good luck... I've started rewriting the Planet in Scheme: https://github.com/lassik/another-planet Help is welcome.

> https://planet.scheme.org/ is still borked.

That sucks :/ Can you find something in the Planet Venus source code that would cause old posts to reappear at the top?

**Comment by amirouche** [comment]
see https://github.com/lassik/another-planet/issues/1

**Comment by amirouche** [comment]
:sob:

**Pull request merged**
