### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by wasamasa**
Some blogs raise errors when fetched. I could only find one of them on the web again.

### CODE REVIEW

**Comment by lassik** [comment]
Thanks a lot for doing the legwork.

We inherited the list from @soegaard. I commented out of many of the missing blogs, but apparently not all.

**Comment by lassik** [comment]
Offer still stands to get ssh to the server if you want it.

**Comment by arthurgleckler** [comment]
Looks good.

**Comment by wasamasa** [comment]
> Offer still stands to get ssh to the server if you want it.

I don't really see the point. I've made an environment with the same issues as the real thing. Fixing things on that server only would introduce a deviation from the repo.

**Pull request merged**
